# Generated by Django 5.0.3 on 2024-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Livro')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('description', models.TextField(max_length=400, verbose_name='Description')),
                ('gender', models.CharField(max_length=100, verbose_name='Gênero')),
                ('image_url', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
